name: Build Kasha Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: codeberg-small
    container:
      image: 'ghcr.io/void-linux/void-mklive:20250116R1'
      options: --privileged
      volumes:
        - /dev:/dev
      env:
        PATH: '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin'

    steps:
      # Este paso debe ir PRIMERO y usar shell puro para evitar dependencias de Node
      - name: Install Node.js and dependencies
        run: |
          xbps-install -Syu xbps
          xbps-install -Syu
          xbps-install -Sy nodejs gcc make pkg-config gtk+3-devel xxd sed coreutils tar

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile project
        run: make

      - name: Create tarball
        run: tar -cvf neko_installer.tar neko_installer

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: neko-installer-package
          path: neko_installer.tar