/*
 * country_data.c
 * Country → Locale/Timezone mapping database
 * Sorted alphabetically by country name
 */
#include "country_data.h"
#include <string.h>
#include <stddef.h>

static const CountryInfo country_list[] = {
    { "Afghanistan",        "ps_AF.UTF-8",  "Asia",      "Kabul"         },
    { "Albania",            "sq_AL.UTF-8",  "Europe",    "Tirane"        },
    { "Algeria",            "ar_DZ.UTF-8",  "Africa",    "Algiers"       },
    { "Andorra",            "ca_AD.UTF-8",  "Europe",    "Andorra"       },
    { "Angola",             "pt_AO.UTF-8",  "Africa",    "Luanda"        },
    { "Argentina",          "es_AR.UTF-8",  "America",   "Argentina/Buenos_Aires" },
    { "Armenia",            "hy_AM.UTF-8",  "Asia",      "Yerevan"       },
    { "Australia",          "en_AU.UTF-8",  "Australia", "Sydney"        },
    { "Austria",            "de_AT.UTF-8",  "Europe",    "Vienna"        },
    { "Azerbaijan",         "az_AZ.UTF-8",  "Asia",      "Baku"          },
    { "Bahrain",            "ar_BH.UTF-8",  "Asia",      "Bahrain"       },
    { "Bangladesh",         "bn_BD.UTF-8",  "Asia",      "Dhaka"         },
    { "Belarus",            "be_BY.UTF-8",  "Europe",    "Minsk"         },
    { "Belgium",            "fr_BE.UTF-8",  "Europe",    "Brussels"      },
    { "Bolivia",            "es_BO.UTF-8",  "America",   "La_Paz"        },
    { "Bosnia",             "bs_BA.UTF-8",  "Europe",    "Sarajevo"      },
    { "Brazil",             "pt_BR.UTF-8",  "America",   "Sao_Paulo"     },
    { "Bulgaria",           "bg_BG.UTF-8",  "Europe",    "Sofia"         },
    { "Cambodia",           "km_KH.UTF-8",  "Asia",      "Phnom_Penh"    },
    { "Cameroon",           "fr_CM.UTF-8",  "Africa",    "Douala"        },
    { "Canada",             "en_CA.UTF-8",  "America",   "Toronto"       },
    { "Chile",              "es_CL.UTF-8",  "America",   "Santiago"      },
    { "China",              "zh_CN.UTF-8",  "Asia",      "Shanghai"      },
    { "Colombia",           "es_CO.UTF-8",  "America",   "Bogota"        },
    { "Congo (DRC)",        "fr_CD.UTF-8",  "Africa",    "Kinshasa"      },
    { "Costa Rica",         "es_CR.UTF-8",  "America",   "Costa_Rica"    },
    { "Croatia",            "hr_HR.UTF-8",  "Europe",    "Zagreb"        },
    { "Cuba",               "es_CU.UTF-8",  "America",   "Havana"        },
    { "Cyprus",             "el_CY.UTF-8",  "Asia",      "Nicosia"       },
    { "Czech Republic",     "cs_CZ.UTF-8",  "Europe",    "Prague"        },
    { "Denmark",            "da_DK.UTF-8",  "Europe",    "Copenhagen"    },
    { "Dominican Republic", "es_DO.UTF-8",  "America",   "Santo_Domingo" },
    { "Ecuador",            "es_EC.UTF-8",  "America",   "Guayaquil"     },
    { "Egypt",              "ar_EG.UTF-8",  "Africa",    "Cairo"         },
    { "El Salvador",        "es_SV.UTF-8",  "America",   "El_Salvador"   },
    { "Estonia",            "et_EE.UTF-8",  "Europe",    "Tallinn"       },
    { "Ethiopia",           "am_ET.UTF-8",  "Africa",    "Addis_Ababa"   },
    { "Finland",            "fi_FI.UTF-8",  "Europe",    "Helsinki"      },
    { "France",             "fr_FR.UTF-8",  "Europe",    "Paris"         },
    { "Georgia",            "ka_GE.UTF-8",  "Asia",      "Tbilisi"       },
    { "Germany",            "de_DE.UTF-8",  "Europe",    "Berlin"        },
    { "Ghana",              "en_GH.UTF-8",  "Africa",    "Accra"         },
    { "Greece",             "el_GR.UTF-8",  "Europe",    "Athens"        },
    { "Guatemala",          "es_GT.UTF-8",  "America",   "Guatemala"     },
    { "Haiti",              "fr_HT.UTF-8",  "America",   "Port-au-Prince"},
    { "Honduras",           "es_HN.UTF-8",  "America",   "Tegucigalpa"   },
    { "Hong Kong",          "zh_HK.UTF-8",  "Asia",      "Hong_Kong"     },
    { "Hungary",            "hu_HU.UTF-8",  "Europe",    "Budapest"      },
    { "Iceland",            "is_IS.UTF-8",  "Atlantic",  "Reykjavik"     },
    { "India",              "hi_IN.UTF-8",  "Asia",      "Kolkata"       },
    { "Indonesia",          "id_ID.UTF-8",  "Asia",      "Jakarta"       },
    { "Iran",               "fa_IR.UTF-8",  "Asia",      "Tehran"        },
    { "Iraq",               "ar_IQ.UTF-8",  "Asia",      "Baghdad"       },
    { "Ireland",            "en_IE.UTF-8",  "Europe",    "Dublin"        },
    { "Israel",             "he_IL.UTF-8",  "Asia",      "Jerusalem"     },
    { "Italy",              "it_IT.UTF-8",  "Europe",    "Rome"          },
    { "Jamaica",            "en_JM.UTF-8",  "America",   "Jamaica"       },
    { "Japan",              "ja_JP.UTF-8",  "Asia",      "Tokyo"         },
    { "Jordan",             "ar_JO.UTF-8",  "Asia",      "Amman"         },
    { "Kazakhstan",         "kk_KZ.UTF-8",  "Asia",      "Almaty"        },
    { "Kenya",              "sw_KE.UTF-8",  "Africa",    "Nairobi"       },
    { "Kuwait",             "ar_KW.UTF-8",  "Asia",      "Kuwait"        },
    { "Latvia",             "lv_LV.UTF-8",  "Europe",    "Riga"          },
    { "Lebanon",            "ar_LB.UTF-8",  "Asia",      "Beirut"        },
    { "Libya",              "ar_LY.UTF-8",  "Africa",    "Tripoli"       },
    { "Lithuania",          "lt_LT.UTF-8",  "Europe",    "Vilnius"       },
    { "Luxembourg",         "fr_LU.UTF-8",  "Europe",    "Luxembourg"    },
    { "Malaysia",           "ms_MY.UTF-8",  "Asia",      "Kuala_Lumpur"  },
    { "Mexico",             "es_MX.UTF-8",  "America",   "Mexico_City"   },
    { "Moldova",            "ro_MD.UTF-8",  "Europe",    "Chisinau"      },
    { "Mongolia",           "mn_MN.UTF-8",  "Asia",      "Ulaanbaatar"   },
    { "Montenegro",         "sr_ME.UTF-8",  "Europe",    "Podgorica"     },
    { "Morocco",            "ar_MA.UTF-8",  "Africa",    "Casablanca"    },
    { "Mozambique",         "pt_MZ.UTF-8",  "Africa",    "Maputo"        },
    { "Myanmar",            "my_MM.UTF-8",  "Asia",      "Yangon"        },
    { "Nepal",              "ne_NP.UTF-8",  "Asia",      "Kathmandu"     },
    { "Netherlands",        "nl_NL.UTF-8",  "Europe",    "Amsterdam"     },
    { "New Zealand",        "en_NZ.UTF-8",  "Pacific",   "Auckland"      },
    { "Nicaragua",          "es_NI.UTF-8",  "America",   "Managua"       },
    { "Nigeria",            "en_NG.UTF-8",  "Africa",    "Lagos"         },
    { "North Macedonia",    "mk_MK.UTF-8",  "Europe",    "Skopje"        },
    { "Norway",             "nb_NO.UTF-8",  "Europe",    "Oslo"          },
    { "Oman",               "ar_OM.UTF-8",  "Asia",      "Muscat"        },
    { "Pakistan",           "ur_PK.UTF-8",  "Asia",      "Karachi"       },
    { "Panama",             "es_PA.UTF-8",  "America",   "Panama"        },
    { "Paraguay",           "es_PY.UTF-8",  "America",   "Asuncion"      },
    { "Peru",               "es_PE.UTF-8",  "America",   "Lima"          },
    { "Philippines",        "en_PH.UTF-8",  "Asia",      "Manila"        },
    { "Poland",             "pl_PL.UTF-8",  "Europe",    "Warsaw"        },
    { "Portugal",           "pt_PT.UTF-8",  "Europe",    "Lisbon"        },
    { "Puerto Rico",        "es_PR.UTF-8",  "America",   "Puerto_Rico"   },
    { "Qatar",              "ar_QA.UTF-8",  "Asia",      "Qatar"         },
    { "Romania",            "ro_RO.UTF-8",  "Europe",    "Bucharest"     },
    { "Russia",             "ru_RU.UTF-8",  "Europe",    "Moscow"        },
    { "Saudi Arabia",       "ar_SA.UTF-8",  "Asia",      "Riyadh"        },
    { "Senegal",            "fr_SN.UTF-8",  "Africa",    "Dakar"         },
    { "Serbia",             "sr_RS.UTF-8",  "Europe",    "Belgrade"      },
    { "Singapore",          "en_SG.UTF-8",  "Asia",      "Singapore"     },
    { "Slovakia",           "sk_SK.UTF-8",  "Europe",    "Bratislava"    },
    { "Slovenia",           "sl_SI.UTF-8",  "Europe",    "Ljubljana"     },
    { "South Africa",       "en_ZA.UTF-8",  "Africa",    "Johannesburg"  },
    { "South Korea",        "ko_KR.UTF-8",  "Asia",      "Seoul"         },
    { "Spain",              "es_ES.UTF-8",  "Europe",    "Madrid"        },
    { "Sri Lanka",          "si_LK.UTF-8",  "Asia",      "Colombo"       },
    { "Sudan",              "ar_SD.UTF-8",  "Africa",    "Khartoum"      },
    { "Sweden",             "sv_SE.UTF-8",  "Europe",    "Stockholm"     },
    { "Switzerland",        "de_CH.UTF-8",  "Europe",    "Zurich"        },
    { "Syria",              "ar_SY.UTF-8",  "Asia",      "Damascus"      },
    { "Taiwan",             "zh_TW.UTF-8",  "Asia",      "Taipei"        },
    { "Tanzania",           "sw_TZ.UTF-8",  "Africa",    "Dar_es_Salaam" },
    { "Thailand",           "th_TH.UTF-8",  "Asia",      "Bangkok"       },
    { "Trinidad & Tobago",  "en_TT.UTF-8",  "America",   "Port_of_Spain" },
    { "Tunisia",            "ar_TN.UTF-8",  "Africa",    "Tunis"         },
    { "Turkey",             "tr_TR.UTF-8",  "Europe",    "Istanbul"      },
    { "Uganda",             "en_UG.UTF-8",  "Africa",    "Kampala"       },
    { "Ukraine",            "uk_UA.UTF-8",  "Europe",    "Kiev"          },
    { "United Arab Emirates","ar_AE.UTF-8", "Asia",      "Dubai"         },
    { "United Kingdom",     "en_GB.UTF-8",  "Europe",    "London"        },
    { "United States",      "en_US.UTF-8",  "America",   "New_York"      },
    { "Uruguay",            "es_UY.UTF-8",  "America",   "Montevideo"    },
    { "Uzbekistan",         "uz_UZ.UTF-8",  "Asia",      "Tashkent"      },
    { "Venezuela",          "es_VE.UTF-8",  "America",   "Caracas"       },
    { "Vietnam",            "vi_VN.UTF-8",  "Asia",      "Ho_Chi_Minh"   },
    { "Yemen",              "ar_YE.UTF-8",  "Asia",      "Aden"          },
    { "Zambia",             "en_ZM.UTF-8",  "Africa",    "Lusaka"        },
    { "Zimbabwe",           "en_ZW.UTF-8",  "Africa",    "Harare"        },
};

static const int country_count = sizeof(country_list) / sizeof(country_list[0]);

const CountryInfo* get_country_list(int *count) {
    if (count) *count = country_count;
    return country_list;
}

const CountryInfo* find_country_by_name(const char *name) {
    if (!name) return NULL;
    for (int i = 0; i < country_count; i++) {
        if (strcmp(country_list[i].name, name) == 0) {
            return &country_list[i];
        }
    }
    return NULL;
}
